version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install cookiecutter
          command: pip install --upgrade pip pip-tools cookiecutter

      - run:
          name: Bootstrap the project
          command: make test

workflows:
  version: 2
  ci:
    jobs:
      - build
