name: NoHopeAhead

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  workflow_dispatch:

    jobs:  
     docker:  
      runs-on: ubuntu-latest

    steps:     
      - uses: actions/checkout@v2
      
      - name: Install requirements
        run: docker-compose up -d --build
